Fix links
MinecraftForge/Documentation pull request #184
Opened 2018-08-07 16:53 UTC by CJMinecraft01

The links did not go to the correct place (they gave a 404 error) so I have found the correct links 😄

2018-08-18 17:39 UTC, tterrag1098 requested changes

2018-08-18 17:39 UTC, tterrag1098 commented on docs/gettingstarted/autoupdate.md
> +Two concrete examples can be seen here for [Charset](https://asie.pl/files/minecraft/update/charset.json) and [Botania Unofficial](https://raw.githubusercontent.com/williewillus/Botania/HEAD/version/
I wouldn't use a `HEAD` ref here, as that could change. Please link to a specific commit so that the URL does not break again...

2018-08-19 12:56 UTC, CJMinecraft01 reviewed
I've changed the branch from HEAD to master. Also for a non raw link you could use this: https://github.com/williewillus/Botania/blob/master/version/update.json

2018-10-11 02:38 UTC, tterrag1098 commented
Sorry, master is not sufficient. You should use a specific commit.

2018-10-18 12:27 UTC, CJMinecraft01 commented
Should have changed it now to this: https://raw.githubusercontent.com/williewillus/Botania/8e86d126e10e862c032242074211b297aede087b/version/update.json sorry about that :D

2020-01-08 23:58 UTC, closed without merging