Improve Events section
MinecraftForge/Documentation pull request #242
Opened 2020-01-08 18:00 UTC by Aeltumn

I'm going to give every section a pass getting it up-to-date with 1.14 whenever I've got some time.

Here are some tiny improvements to the Events section, I've added some information and an example on how to use the properties of the Mod.EventBusSubscriber annotation to your advantage to register client-only events. This will hopefully aid people separating their client/common classes because they use the annotation instead.

2020-01-21 01:17 UTC, tterrag1098 requested changes
This could use a bit more documentation on the mod bus, and which types of events use it.

2020-01-21 01:17 UTC, tterrag1098 commented on docs/events/intro.md
> +    This does not register an instance of the class; it registers the class itself (i.e. the event handling methods must be static.
Don't remove that paren

2020-01-21 18:07 UTC, tterrag1098 requested changes

2020-01-21 18:07 UTC, tterrag1098 commented on docs/events/intro.md
> +The mod event bus is primarily meant for listening to lifecycle events in which mods should initialize. Many of these events are also ran in parallel so mods can be initialized at the same time. This
The mod event bus is used for all events that are only called during the load process. This includes lifecycle events yes, but also registry events, and other misc load-time events like color handlers and model bake etc.

2020-01-21 18:07 UTC, tterrag1098 commented on docs/events/intro.md
> +The mod event bus is primarily meant for listening to lifecycle events in which mods should initialize. Many of these events are also ran in parallel so mods can be initialized at the same time. This
Also perhaps mention DeferredWorkQueue

2020-01-22 00:30 UTC, Aeltumn commented
I'm not super familiar with the mod event bus, I've been using the system wrong myself until very recently, so the information might be a bit lacklustre.

2020-01-26 18:40 UTC, tterrag1098 approved these changes

2020-01-26 18:40 UTC, merged