Small fixes + add info about DeferredRegister
MinecraftForge/Documentation pull request #249
Opened 2020-01-16 04:57 UTC by Cadiboo

Fixes reference to "print", changes `EntityEntry` to `EntityType`, adds info about `TileEntity` registration and adds info about DeferredRegister.

2020-01-21 01:10 UTC, tterrag1098 requested changes
Please rebase this to 1.14.x

2020-01-21 01:10 UTC, tterrag1098 commented on docs/concepts/registries.md
> +The recommended way to register things is through the `RegistryEvent`s. These [events][] are fired after mod constructors are called and before configs are loaded, In `RegistryEvent.NewRegistry`, reg
"... before configs are loaded, In `RegistryEvent.NewRegistry`..." should be the end/beginning of a sentence, not a comma.

2020-01-21 02:29 UTC, tterrag1098 submitted a review, later dismissed

2020-01-24 05:11 UTC, Cadiboo commented
Rebased to 1.14.x.

2020-01-27 05:07 UTC, tterrag1098 approved these changes

2020-01-27 05:07 UTC, merged