Fix TileEntity references for 1.13+
MinecraftForge/Documentation pull request #250
Opened 2020-01-16 05:34 UTC by Cadiboo

2020-01-21 01:06 UTC, tterrag1098 requested changes
Please rebase this to 1.14.x

2020-01-21 01:06 UTC, tterrag1098 commented on docs/tileentities/tileentity.md
> +IForgeBlock#hasTileEntity(Blockstate state)
It's `BlockState`

2020-01-21 01:06 UTC, tterrag1098 commented on docs/tileentities/tileentity.md
> +  TileEntityType<?> type = TileEntityType.Builder.create(<factory>, <block...>).build(null);
Use valid syntax here, or at least a comment

2020-01-21 01:06 UTC, tterrag1098 commented on docs/tileentities/tileentity.md
> +The `flags` are a bitmask and should contain 2, which will sync the changes to the client.
Perhaps mention `Constants.BlockFlags`

2020-01-21 02:28 UTC, tterrag1098 requested changes

2020-01-21 02:28 UTC, tterrag1098 commented on docs/tileentities/tileentity.md
> +In this example, `factory` is a function that creates a new instance of your TileEntity. A method reference or a lamda is commonly used. The variable `validBlocks` is one or more blocks (`TileEntityT
lambda*

2020-01-21 18:09 UTC, tterrag1098 commented
Looks good, but it still needs to be rebased.

2020-01-24 05:09 UTC, Cadiboo commented
Rebased to 1.14.x.

2020-04-22 04:17 UTC, tterrag1098 approved these changes

2020-04-22 04:17 UTC, merged