Update Item to use Item.Properties
MinecraftForge/Documentation pull request #252
Opened 2020-01-16 06:02 UTC by Cadiboo

2020-01-21 01:03 UTC, tterrag1098 requested changes
Please rebase this to 1.14.x

2020-01-21 01:03 UTC, tterrag1098 commented on docs/items/items.md
> +|      `addToolType`     | Adds a pair of harvest tool type (`"shovel"`, `"axe"`) and harvest level. |
This does not accept a string anymore

2020-01-21 02:28 UTC, tterrag1098 submitted a review, later dismissed

2020-01-24 05:08 UTC, Cadiboo commented
Rebased to 1.14.x.

2020-01-27 05:07 UTC, tterrag1098 approved these changes

2020-01-27 05:07 UTC, merged