Updated Environment Setup instructions for IntelliJ
MinecraftForge/Documentation pull request #260
Opened 2020-02-08 23:00 UTC by TheGreyGhost

The gradle tasks have been changed since the original instructions were written.  IDEA 2019 also performs most of the setup without manual tweaks required.

2020-02-19 23:01 UTC, tterrag1098 requested changes
I see no reason to keep information that is over a year old. We can expect people to be on a decently new version of IntelliJ. If you want, make a note that it only works on 2019+.

2020-02-20 13:14 UTC, TheGreyGhost commented
OK, you mean - delete the "IDEA older versions" section, and just leave the "IDEA 2019" section?

Thanks very much for the docs by the way.  They sure have helped me a lot.

2020-03-29 13:00 UTC, EmmanuelMess commented on docs/forgedev/index.md
> +   1. open the Gradle sidebar on the right hand side of your screen, then open the `forge` project tree, select `Tasks`, then `other` and double-click the `setup` task (may also appear as `MinecraftF
This should be left as an alternative IMO.

2020-03-29 13:06 UTC, EmmanuelMess commented on docs/forgedev/index.md
> +#### IDEA older versions
You should add a disclamer to the top that "only 2019 and newer versions should be used"

2020-04-22 04:19 UTC, tterrag1098 commented
> OK, you mean - delete the "IDEA older versions" section, and just leave the "IDEA 2019" section?

Yes. And perhaps futureproof that definition with "2019+"

2020-04-26 08:09 UTC, TheGreyGhost commented
Updated as requested...

2020-04-26 20:07 UTC, tterrag1098 approved these changes

2020-04-26 20:07 UTC, merged