Updated the class name of TranslationTextComponent
MinecraftForge/Documentation pull request #298
Opened 2020-05-23 10:59 UTC by GeldornOfDragonhill

Just a name update for 1.15

2020-06-18 18:47 UTC, Aeltumn approved these changes

2020-06-18 18:47 UTC, Aeltumn commented on docs/concepts/internationalization.md
> +- `createComponentTranslation(ICommandSender, String, Object...)` creates a localized and formatted `ITextComponent` depending on a receiver. The localization and formatting is done eagerly if the re
`ICommandSender` changed to `ICommandSource`

2020-06-18 18:47 UTC, Aeltumn commented on docs/concepts/internationalization.md
> +- `createComponentTranslation(ICommandSender, String, Object...)` creates a localized and formatted `ITextComponent` depending on a receiver. The localization and formatting is done eagerly if the re
The method returns a `TextComponent`, not a `ITextComponent`

2020-06-20 10:54 UTC, Aeltumn commented
I forgot to add a comment to my review the other day. I think this PR is fine but you could update the other names too.

2020-07-18 05:52 UTC, tterrag1098 requested changes
Please be thorough and update all the class names in this area.

2020-07-18 05:52 UTC, tterrag1098 commented
Also, this should target 1.14.x if it's relevant there.

2021-01-10 04:03 UTC, sciwhiz12 commented
This PR has been superseded by #331; closing.

2021-01-10 04:03 UTC, closed without merging