Update Getting Started
MinecraftForge/Documentation pull request #299
Opened 2020-05-23 14:49 UTC by allc

Fix indentation so the lists should show correctly on Read The Docs

  - The style guides say to have two spaces for indentation, I used four spaces here just to be consistent with many of other pages in this guide (at least also with rest of this page)

Mention command for generating configurations in VS Code
Mention to edit `eula.txt` for testing the server

  - Think it is helpful to mention it, and it does not seem to appear in the error message

2020-06-18 18:39 UTC, Aeltumn submitted a review, later dismissed
Good change to also mention you can use VS Code now. Although I don't know if it's important to mention you have to accept the eula, that should be obvious.

2020-07-18 05:53 UTC, tterrag1098 commented
The indentation was fixed by #301, move this to 1.14.x and apply only your content changes, and this would still be okay to merge.

2020-07-21 14:17 UTC, allc commented
@tterrag1098 Thanks for the comment.
I have changed the base branch to 1.14.x and edited the commits so there is only content changes in this PR.

2021-01-10 05:36 UTC, sciwhiz12 requested changes
Please rebase this PR to the 1.15.x branch, as 1.14.x is out-of-support.
_(If you do not wish to continue this PR, please respond soon.)_

2021-01-10 05:36 UTC, sciwhiz12 commented on docs/gettingstarted/index.md
> +    * Forge explicitly supports developing with Eclipse, IntelliJ or Visual Studio Code environments, but any environment, from Netbeans to vi/emacs, can be made to work.
Forge does not officially provide support for developing in Visual Studio Code. Although the run task exists, it is expected that users who wish to use VS Code for making Forge mods must solve any issues that arise from their use of VS Code by themselves (or through other community members).

Please revert this change, and add an admonition after the `genVSCodeRuns` paragraph to warn users of this.
(See the `Customizing Your Mod Information` section for an example of an admonition, the `!!! important` part)

2021-06-21 18:55 UTC, ChampionAsh5357 commented
Merged in the omnibus #364.

2021-06-21 18:55 UTC, closed without merging