[1.18] Improve DistExecutor explanation
MinecraftForge/Documentation pull request #406
Opened 2022-02-11 22:04 UTC by ChampionAsh5357

Currently, the methods within `DistExecutor` are glossed over. While the javadocs do provide a little more in-depth explanation to its usage, the basics of what the class does and how to use should be provided within the documentation.

Additionally, this also gives a warning about the changes to `invokedynamic` causing all `#safe*` variants not to work properly.

2022-02-12 02:32 UTC, sciwhiz12 requested changes

2022-02-12 02:32 UTC, sciwhiz12 commented on docs/concepts/sides.md
> +These two methods are subdivided further into `#safe*` and `#unsafe*` variants. Safe and unsafe variants are misnomers for their purposes. The main difference is that when in a development environmen
This should include an example of a "a lambda returning a method reference to another class", for demonstrative purposes.

2022-02-12 02:32 UTC, sciwhiz12 commented on docs/concepts/sides.md
> +`DistExecutor` functions by taking in a supplied supplier executing a method, effectively preventing classloading by taking advantage of the [`invokedynamic` JVM instruction][invokedynamic]. The exec
This is a bit pedantic, but the word `functions` as a verb should be changed to avoid collision with the word `functions` as a noun.

2022-02-12 10:14 UTC, sciwhiz12 approved these changes

2022-02-20 23:57 UTC, TheCurle approved these changes

2022-02-20 23:57 UTC, merged