[1.16.x] Upstream #409: Add info for registering to vanilla registries
MinecraftForge/Documentation pull request #413
Opened 2022-02-23 22:07 UTC by ChampionAsh5357

Port of #409 to 1.16.

> There are quite a few registries that are not forge registries so it's useful to have something to point people to.

2022-02-23 23:57 UTC, sciwhiz12 requested changes

2022-02-23 23:57 UTC, sciwhiz12 commented on docs/concepts/registries.md
> +Due to some peculiarities of vanilla code, not all registries are wrapped by Forge. These can be static registries, like `RecipeType`, which are safe to use. There are also dynamic registries, like `
Change use of Mojmap class name to MCP class name:
```suggestion
Due to some peculiarities of vanilla code, not all registries are wrapped by Forge. These can be static registries, like `IRecipeType`, which are safe to use. There are also dynamic registries, like `ConfiguredFeature` and some other worldgen registries, which are typically represented in JSON. These objects should only be registered this way if there is another registry object that requires it. 
```

2022-02-24 02:46 UTC, sciwhiz12 approved these changes

2022-03-06 14:22 UTC, TheCurle approved these changes

2022-03-06 14:22 UTC, merged