Added other Item Property Methods
MinecraftForge/Documentation pull request #505
Opened 2023-07-15 13:30 UTC by Asbestosstar

This adds the other methods in Item$Properties

2023-09-14 00:22 UTC, ChampionAsh5357 requested changes

2023-09-14 00:22 UTC, ChampionAsh5357 commented on docs/items/index.md
> +| `food`         | Makes the item eatable and is used to store information about the Hunger and Effects. |
This sentence could probably be reworded to explain the concept better. Probably something that mentions FoodData iirc the class correctly.

2023-09-14 00:22 UTC, ChampionAsh5357 commented on docs/items/index.md
> +| `defaultDurability`       | Sets the Item Durability for if it has a Maximum Damage of 0.
```suggestion
| `defaultDurability`       | Sets the durability of an item, assuming the item isn't stackable.
```

2023-09-14 00:22 UTC, ChampionAsh5357 commented on docs/items/index.md
> +| `rarity`         | Sets the Item Name Color in the ToolTip based on Rarity.
```suggestion
| `rarity`         | Sets the rarity of an item. This currently only changes the color of the item name in the tooltip.
```

2023-09-14 00:22 UTC, ChampionAsh5357 commented on docs/items/index.md
> +| `fireResistant`         | Makes it so the item is resistant to fire.
Does this include lava or just fire blocks?

2023-09-14 00:22 UTC, ChampionAsh5357 commented on docs/items/index.md
> +| `setNoRepair`         | Makes the item impossible to Repair.
```suggestion
| `setNoRepair`         | Makes the item impossible to repair, assuming it has durability.
```

2025-01-04 15:48 UTC, PaintNinja commented
Closing as stale

2025-01-04 15:48 UTC, closed without merging