Basic update for 1.21.1, improve tags documentation
MinecraftForge/Documentation pull request #532
Opened 2024-10-12 22:08 UTC by PaintNinja

This PR does some basic updates to the documentation for 1.21.1, including:
- FMLJavaModLoadingContext as constructor parameter
- clientSideOnly in mods.toml
- Deprecation of services in mods.toml
- ResourceLocation changes
- Monitor event phase/priority
- Java 21
- Where to find tags

2024-10-12 22:22 UTC, Jonathing requested changes

2024-10-12 22:22 UTC, Jonathing commented on docs/concepts/registries.md
> +public static final RegistryObject<Item> BOW = RegistryObject.create(ResourceLocation.fromNamespaceAndPath("minecraft", "bow"), ForgeRegistries.ITEMS);
Please replace `"minecraft"` with `ResourceLocation.DEFAULT_NAMESPACE`, or use a different example namespace like `"examplemod"`.

2024-10-12 22:28 UTC, Jonathing approved these changes

2024-10-13 06:30 UTC, LexManos commented on docs/misc/updatechecker.md
> +- Some examples can be found here for [nocubes][] and [Corail Tombstone][corail].
Why not just use forge's promotions-slim.json as the example? Doesn't have a changelog, but its a good enough example for the basic use.

2024-10-13 13:38 UTC, merged