Added information about ItemStacks to capabilities
MinecraftForge/Documentation pull request #89
Opened 2017-02-05 06:13 UTC by Denyol

The Capabilities doc now has more information about adding custom inventories to a ItemStack, this was added because I was having trouble understanding how to add inventories to ItemStacks and makes the specific documentation more understandable.

2017-02-05 07:13 UTC, elifoster requested changes

2017-02-05 07:13 UTC, elifoster commented on docs/datastorage/capabilities.md
> +In the case of exposing a capability to an custom ItemStack of your mod, it is required that the `Item` class overrides `initCapabilities` to return a custom class implementing `ICapabilityProvider`.
`an custom` -> `a custom`

Missing space between `ICapabilityProvider` and `needs`

2017-02-05 07:28 UTC, Denyol commented on docs/datastorage/capabilities.md
> +In the case of exposing a capability to an custom ItemStack of your mod, it is required that the `Item` class overrides `initCapabilities` to return a custom class implementing `ICapabilityProvider`.
Added, thank you for the input.

2017-04-19 17:43 UTC, tterrag1098 commented
I think this would be better inside an admonition, as it is more of a warning/footnote and just having it as a simple paragraph makes it easy to miss.

2020-01-08 23:58 UTC, closed without merging