Update index.md
MinecraftForge/Documentation pull request #91
Opened 2017-03-05 20:49 UTC by 6NGB

Using Forge with NetBeans. Original method found at https://blogs.oracle.com/geertjan/entry/seamless_minecraft_forge_in_netbeans .
Regards!

2017-03-05 21:57 UTC, elifoster requested changes

2017-03-05 21:57 UTC, elifoster commented on docs/gettingstarted/index.md
> +3. Make sure gradle's task finished properly. If not - consult it's output to fix erors (common issues are firewall and the `JAVA_HOME` environment variable not pointing to a valid JDK);
* `If not -` should be `If not,`
* `it's output` should be `its output`
* `erors` should be `errors`

2017-03-05 21:57 UTC, elifoster commented on docs/gettingstarted/index.md
> +4. Make sure your NetBeans has the _Gradle Support_ plugin, available from NB's _Plugin Portal_. Install it and restart NB if needed (To install a NB plugin, open the IDE and select _Tools > Plugins_
Perhaps link to the plugin

2017-03-05 21:57 UTC, elifoster commented on docs/gettingstarted/index.md
> +5. Inside NB, shoose _File > Open Project_ and select the Forge MDK/SRC extraction you made earlier. If everything is OK, it'll appear with gradle's circle icon;
* `shoose` should be `choose`
* `gradle's` should be `Gradle's`

2017-03-05 21:57 UTC, elifoster commented on docs/gettingstarted/index.md
> +7. Enjoy!
Possibly unnecessary fluff.

2017-03-06 15:58 UTC, 6NGB commented
@elifoster Thanks for reviewing. Please check updated version.

2017-04-19 17:40 UTC, tterrag1098 commented
These instructions duplicate a lot of what is said above. I think they should be mixed in as sub-bullets like the eclipse/IDEA instructions, instead of as a separate section entirely.

2020-01-08 23:58 UTC, closed without merging